spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Michael8833
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    # Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update